name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Configure Git identity
        run: |
          git config --global user.name "DreamsWave"
          git config --global user.email "dreamswave.dev@gmail.com"

      - name: Run standard-version
        run: bunx standard-version # Use bunx instead of npx

      - name: Push changes
        run: |
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
